### ISSUE TITLE
No module named 'pythx.middleware.property_checking'

### ISSUE THREAD

**Issue by maurelian** [dmuhs/mythx-cli#129]
* MythX CLI version: 0.6.14
* Python version: 3.7.5
* Operating System: MacOS Catalina

### Description

Trying to run `$ mythx analyze --check-properties code/contracts/proxies/CmpPriceProvider.sol`

got:

```
Traceback (most recent call last):
  File "/Users/primary/.pyenv/versions/3.7.5/bin/mythx", line 5, in <module>
    from mythx_cli.cli import cli
  File "/Users/primary/.pyenv/versions/3.7.5/lib/python3.7/site-packages/mythx_cli/cli.py", line 15, in <module>
    from mythx_cli.analyze.command import analyze
  File "/Users/primary/.pyenv/versions/3.7.5/lib/python3.7/site-packages/mythx_cli/analyze/command.py", line 10, in <module>
    from pythx.middleware.property_checking import PropertyCheckingMiddleware
ModuleNotFoundError: No module named 'pythx.middleware.property_checking'
```

**Comment by dmuhs** [comment]
Could you perform `pip freeze | grep pythx` and see if the version is `1.5.7`? If not, you will have to run `pip install -U pythx` to update to the latest release. This should also be done automatically if you run `pip install -f -U mythx-cli`

**Comment by maurelian** [comment]
working now.

**Comment by dmuhs** [comment]
🎉
