### ISSUE TITLE
Update dependency Jinja2 to v3

### ISSUE THREAD

**Issue by softskillpro** [dmuhs/mythx-cli#267]
* MythX CLI version: 0.6.22
* Python version: 3.8
* Operating System: GitHub Workflow

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.
I'm using mythx-cli in GitHub workflow. But pip-cli is upgraded from 21 to 22, it doesn't work.
The reason is jinja2 is old.
Please check this.
https://github.com/pallets/jinja/issues/1585

### What I Did

```
Run mythx --api-key *** \
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/bin/mythx", line 5, in <module>
    from mythx_cli.cli import cli
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/mythx_cli/cli.py", line 21, in <module>
    from mythx_cli.render.command import render
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/mythx_cli/render/command.py", line 7, in <module>
    import jinja2
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F[40](https://github.com/upstateinteractive/perfectpool-dao/runs/5543485952?check_suite_focus=true#step:8:40)1
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/markupsafe/__init__.py)
Error: Process completed with exit code 1.
```

**Comment by moodysalem** [comment]
also running into this
