### ISSUE TITLE
MythX cannot be executed after installed.

### ISSUE THREAD

**Issue by santai-wang-7senses** [dmuhs/mythx-cli#268]
* MythX CLI version: 0.6.22
* Python version: 3.9.1
* Operating System: macOS 12.1 Monterey

### Description

I followed mythx-cli documentation to install mythx-cli. No matter what command typed in, mythx-cli only shows the Traceback message.

### What I Did

```
~:pip3 install mythx-cli
~:mythx analyze --help

Traceback (most recent call last):
  File "/opt/homebrew/bin/mythx", line 5, in <module>
    from mythx_cli.cli import cli
  File "/opt/homebrew/lib/python3.9/site-packages/mythx_cli/cli.py", line 21, in <module>
    from mythx_cli.render.command import render
  File "/opt/homebrew/lib/python3.9/site-packages/mythx_cli/render/command.py", line 7, in <module>
    import jinja2
  File "/opt/homebrew/lib/python3.9/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/opt/homebrew/lib/python3.9/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/opt/homebrew/lib/python3.9/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/opt/homebrew/lib/python3.9/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/opt/homebrew/lib/python3.9/site-packages/markupsafe/__init__.py)
```

**Comment by crichmond1989** [comment]
I have this issue as well.

- MythX CLI version: 0.6.22
- Python version: 3.8.3
- Operating System: Windows 10

**Comment by santai-wang-7senses** [comment]
Updated: The version of package "markupsafe" has been upgraded to 2.1.1 and it's not compatible to mythx-cli

This command will fix the problem:
```
pip3 install markupsafe==2.0.1
```

**Comment by chahakshahcs5** [comment]
Still getting the error @santai-wang-7senses 
![image](https://user-images.githubusercontent.com/76069775/167224253-623d3999-b5ca-4920-9ff7-c3c8920b4fc5.png)
